config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resource :wechat, only: %i( show create )
  namespace :wechat do
    resources :stores, only: %i( index show )
    resource :cart, only: :destroy do
      collection do
        post :add, path: 'add/:id'
        delete :minus, path: 'minus/:id'
      end
    end
    resources :users, only: %i( show )
    resources :orders, only: %i( new index show create destroy )
    resources :addresses
    resource :payment, only: %i( new create show) do
      get :done
      post :notify
    end
  end
  get 'auth/wechat/callback', to: 'home#wechat'

  devise_for :users, :controllers => {
      :omniauth_callbacks => "users/omniauth_callbacks",
  }

  resources :users, except: %i( new create ) do
    member do
      patch :rolify
    end
  end
  resources :menus do
    member do
      get 'pictures', to: 'menus#list'
      post 'pictures', to: 'menus#upload'
      delete 'pictures/:picture_id', to: 'menus#remove'

      post :publish
      post :unpublish
    end
  end
  resources :locations
  resources :stores
  resources :orders do
    member do
      post :confirm
    end
  end

  require 'sidekiq/web'
  authenticate :user, lambda {|u| u.admin?} do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user
  has_many :menus, dependent: :destroy
  has_many :orders
  belongs_to :location

  has_one :picture, as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :picture, reject_if: :all_blank, allow_destroy: true

  has_many :business_hours, inverse_of: :store, dependent: :destroy
  accepts_nested_attributes_for :business_hours, reject_if: :all_blank, allow_destroy: true

  validates :name,  presence: true, length: { maximum: 255 }
  validates :intro, presence: true, length: { maximum: 255 }

  default_scope -> { order(created_at: :DESC) }

  def store_and_user
    "#{self.user.email} 的商铺：#{name}"
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  load_and_authorize_resource

  def index
    @q = @stores.page(params[:page]).ransack(params[:q])
    @stores = @q.result
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def store_params
      params.require(:store).permit(:name, :intro, :user_id, :location_id,
                                    picture_attributes: [:id, :picture, :imageable_type, :imageable_id],
                                    business_hours_attributes: [:id, :open_at, :close_at, :_destroy])
    end
end

app/controllers/wechat/stores_controller.rb
class Wechat::StoresController < Wechat::BaseController

  def index
    @q = Store.ransack(params[:q])
    @stores = @q.result.includes(:location)
  end

  def show
    @store = Store.find params[:id]
    store_cart = "store#{@store.id}"
    @cart = Cart.from_hash(session[store_cart.to_sym])
    # 删除客服端里的 session 仍然保存着的商家删除或下线的菜品
    @cart.items.delete_if { |item| !item.menu.publish? || item.menu.nil? }
    session[store_cart.to_sym] = @cart.serialize
  end
end

app/helpers/stores_helper.rb
module StoresHelper
  def stores_for_roles
    current_user.admin? ? @stores = Store.all : @stores = current_user.stores
  end
end

app/views/stores/_business_hour_fields.html.erb
<div class="nested-fields">
	<div class="form-group">
		<div class="row">
			<div class="col-4">
				<%= f.label :open_at, '开始时间' %>
				<%= f.time_field :open_at, class: 'form-control' %>

			</div>
			<div class="col-4">
				<%= f.label :close_at, '结束时间' %>
				<%= f.time_field :close_at, class: 'form-control' %>
			</div>
			<div class="col-3 text-right">
				<%= link_to_remove_association "移除此时间段", f, class: 'btn btn-outline-dark btn-sm' %>
			</div>
		</div>
	</div>
</div>

app/views/stores/_form.html.erb
<!-- form start -->
<%= form_with(model: store, local: true) do |form| %>
  <div class="box-body">
    <% if store.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(store.errors.count, "error") %>
        prohibited this store from being saved:
        </h2>

        <ul>
          <% store.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>


    <div class="form-group">
      <%= form.label :name, '*商铺名：' %>
      <%= form.text_field :name, id: :store_name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :intro, '*商铺介绍：' %>
      <%= form.text_field :intro, id: :store_intro, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.fields_for :business_hours do |business_hour| %>
        <%= render 'business_hour_fields', f: business_hour %>
      <% end %>
      <div class="links">
        <%= link_to_add_association('Add Business Hour', form, :business_hours,
                                    class: 'btn btn-outline-dark') %>
      </div>
    </div>


    <% if current_user.admin? %>
      <div class="form-group">
        <%= form.label :user_id, '*商铺老板：' %>
        <%= form.collection_select(:user_id, User.all, :id, :email,
                                   {include_blank: false},
                                   {class: 'form-control'}) %>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :location_id, '*入驻食堂：' %>
      <%= form.collection_select(:location_id, Location.all, :id, :name,
                                 {include_blank: true},
                                 {class: 'form-control'}) %>
    </div>

<% @store.build_picture unless @store.picture %>
    <div class="form-group">
      <%= form.label :picture, '图片：' %>
      <%= form.fields_for :picture do |f| %>
        <%= f.file_field :picture, class: 'form-control' %>
      <% end %>
    </div>

    <div class="box-footer text-right">
      <%= form.submit '确 认', class: 'btn btn-outline-info' %>
    </div>
  <% end %>
  </div>

app/views/stores/_store.html.erb
<style>
  .card:hover {
    box-shadow: 0 0 3px 5px rgba(220, 221, 221, 0.377);
  }
</style>

<div class="card" style="width: 18rem;">

  <% unless store.picture.nil? %>
    <%= image_tag store.picture.url, size: '150x250', class: 'card-img-top' %>
  <% end %>

  <div class="card-body">
    <h4 class="card-title"><%= truncate store.name, length: 17 %></h4>
    <p class="card-text"><%= truncate store.user.email, length: 25 %></p>

    <div class="btn-group btn-group-sm">
      <%= link_to '详情', store, class: 'btn btn-sm btn-outline-dark' %>
      <%= link_to '编辑', edit_store_path(store), class: 'btn btn-sm btn-outline-dark mx-1' %>
      <%= link_to('删除', store, method: :delete,
                  class: 'btn btn-sm btn-outline-danger',
                  data: {confirm: '确认删除？'}) %>
    </div>
  </div>
</div>

app/views/stores/edit.html.erb
<%= content_for :content do %>

  <%= render 'shared/title', title: '编辑商铺' %>
  <div class="row">
    <div class="col-7">
      <div class="card mb-3 border-info">
        <div class="card-body">

          <%= render 'form', store: @store %>

        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/stores/index.html.erb
<%= content_for :content do %>

  <%= render 'shared/title', title: '商铺管理' %>

  <%= search_form_for @q do |f| %>
    <div class="row">
      <div class="col-4">
        <div class="input-group">
          <%= f.search_field :name_cont, class: 'form-control', placeholder: '商铺名' %>
          <span class="input-group-btn">
            <%= f.submit '搜索', class: 'btn btn-outline-dark' %>
          </span>
        </div>
      </div>

      <div class="col-4"> </div>
      <div class="col-4"></div>
    </div>
  <% end %>

  <div class="row">
    <% @stores.each do |store| %>
      <div class="col-4 my-3">
        <%= render store %>
      </div>
    <% end %>
  </div>

  <%= paginate @stores %>

  <div class="fixed-action-btn">
    <%= link_to '+添加商铺', new_store_path, class: 'btn btn-danger' %>
  </div>
<% end %>

app/views/stores/new.html.erb
<%= content_for :content do %>

  <%= render 'shared/title', title: '添加商铺' %>

  <div class="row">
    <div class="col-7">
      <div class="card mb-3 border-info">
        <div class="card-body">
          <h4 class="card-title text-center">添加商铺</h4>
          <%= render 'form', store: @store %>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/stores/show.html.erb
<%= content_for :content do %>
<%= render 'shared/title', title: "#{@store.name} 商铺详情" %>

  <div class="btn-group" role="group">
    <%= link_to '返回', stores_path, class: 'btn btn-sm btn-outline-dark' %>
    <%= link_to '编辑', edit_store_path(@store), class: 'btn btn-sm btn-outline-dark mx-1' %>
    <%= link_to '+添加菜品', new_menu_path(store_id: @store), class: 'btn btn-sm btn-outline-danger' %>
  </div>

  <div class="container">
    <div class="row">
      <% @store.menus.each do |menu| %>
        <div class="col-4 my-3">
          <%= render 'menus/menu', menu: menu %>
        </div>
      <% end %>
    </div>
  </div>

<% end %>