config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resource :wechat, only: %i( show create )
  namespace :wechat do
    resources :stores, only: %i( index show )
    resource :cart, only: :destroy do
      collection do
        post :add, path: 'add/:id'
        delete :minus, path: 'minus/:id'
      end
    end
    resources :users, only: %i( show )
    resources :orders, only: %i( new index show create destroy )
    resources :addresses
    resource :payment, only: %i( new create show) do
      get :done
      post :notify
    end
  end
  get 'auth/wechat/callback', to: 'home#wechat'

  devise_for :users, :controllers => {
      :omniauth_callbacks => "users/omniauth_callbacks",
  }

  resources :users, except: %i( new create ) do
    member do
      patch :rolify
    end
  end
  resources :menus do
    member do
      get 'pictures', to: 'menus#list'
      post 'pictures', to: 'menus#upload'
      delete 'pictures/:picture_id', to: 'menus#remove'

      post :publish
      post :unpublish
    end
  end
  resources :locations
  resources :stores
  resources :orders do
    member do
      post :confirm
    end
  end

  require 'sidekiq/web'
  authenticate :user, lambda {|u| u.admin?} do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/user.rb
class User < ApplicationRecord
  rolify
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :stores, dependent: :destroy
  has_many :menus, through: :stores
  has_many :orders
  has_many :addresses

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end

  def super_admin?
    self.id == 1
  end

  def admin?
    self.has_role? :admin
  end

  def merchant?
    self.has_role? :merchant
  end

  def gender
    self.sex == 1 ? '男' : '女'
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      user.email = "#{auth.uid}@jforder.com"
      user.password = Devise.friendly_token[0,20]
      user.nickname = auth.info.nickname
      user.sex = auth.info.sex
      user.avatar = auth.info.headimgurl
      user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.wechat_data']
        user.provider = data['provider']
        user.uid = data['uid']
        user.nickname = data['info']['nickname']
        user.sex = data['info']['sex']
        user.avatar = data['info']['headimgurl']
      end
    end
  end

  def email_required?
    false
  end

  # ----------- 订单相关 ---------------
  def store_orders
    orders = []
    self.stores.each do |s|
      s.orders.each do |o|
        orders << o if o.confirmed? || o.delivered? || o.refunded?
      end
    end
    orders
  end

  def user_orders
    self.orders.where(active: true)
  end

  def unconfirm_orders
    orders = []
    stores.each do |s|
      s.orders.each do |o|
        orders << o if o.may_confirm?
      end
    end
    orders
  end

  def active_orders
    merchant? ? store_orders : user_orders
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  layout 'wechat'

  def wechat
    @user = User.from_omniauth(request.env['omniauth.auth'])
    sign_in @user, event: :authentication
    session['devise.wechat_data'] = request.env['omniauth.auth']
    redirect_back_or(root_path)
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @q = @users.page(params[:page]).ransack(params[:q])
    @users = @q.result
  end

  def show
  end

  def edit
  end

  def rolify
    @user.role_ids = params[:user][:role_ids]
    redirect_to users_url, notice: '权限修改成功'
  end

  def update
    @user.role_ids = params[:user][:role_ids]
    redirect_to edit_user_path(@user), notice: '权限修改成功'
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: "资料删除成功！"
  end

  private

    def user_params
      params.require(:user).permit(:email, :password)
    end

end

app/controllers/wechat/users_controller.rb
class Wechat::UsersController < Wechat::BaseController
  before_action :confirm_wechat_user

  def show
  end

  private

  def confirm_wechat_user
    unless current_user.provider == 'wechat'
      redirect_to wechat_stores_url
    end
  end

end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/wechat/users_helper.rb
module Wechat::UsersHelper
end

app/views/users/shared/_devise_notices.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= alert %>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "登录", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "注册", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "忘记密码?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "没有收到确认邮件?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>