config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resource :wechat, only: %i( show create )
  namespace :wechat do
    resources :stores, only: %i( index show )
    resource :cart, only: :destroy do
      collection do
        post :add, path: 'add/:id'
        delete :minus, path: 'minus/:id'
      end
    end
    resources :users, only: %i( show )
    resources :orders, only: %i( new index show create destroy )
    resources :addresses
    resource :payment, only: %i( new create show) do
      get :done
      post :notify
    end
  end
  get 'auth/wechat/callback', to: 'home#wechat'

  devise_for :users, :controllers => {
      :omniauth_callbacks => "users/omniauth_callbacks",
  }

  resources :users, except: %i( new create ) do
    member do
      patch :rolify
    end
  end
  resources :menus do
    member do
      get 'pictures', to: 'menus#list'
      post 'pictures', to: 'menus#upload'
      delete 'pictures/:picture_id', to: 'menus#remove'

      post :publish
      post :unpublish
    end
  end
  resources :locations
  resources :stores
  resources :orders do
    member do
      post :confirm
    end
  end

  require 'sidekiq/web'
  authenticate :user, lambda {|u| u.admin?} do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user
  has_many :menus, dependent: :destroy
  has_many :orders
  belongs_to :location

  has_one :picture, as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :picture, reject_if: :all_blank, allow_destroy: true

  has_many :business_hours, inverse_of: :store, dependent: :destroy
  accepts_nested_attributes_for :business_hours, reject_if: :all_blank, allow_destroy: true

  validates :name,  presence: true, length: { maximum: 255 }
  validates :intro, presence: true, length: { maximum: 255 }

  default_scope -> { order(created_at: :DESC) }

  def store_and_user
    "#{self.user.email} 的商铺：#{name}"
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  load_and_authorize_resource

  def index
    @q = @stores.page(params[:page]).ransack(params[:q])
    @stores = @q.result
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def store_params
      params.require(:store).permit(:name, :intro, :user_id, :location_id,
                                    picture_attributes: [:id, :picture, :imageable_type, :imageable_id],
                                    business_hours_attributes: [:id, :open_at, :close_at, :_destroy])
    end
end

app/controllers/wechat/addresses_controller.rb
class Wechat::AddressesController < Wechat::BaseController
  before_action :set_address, only: %i( edit show update destroy )

  def new
    @address = current_user.addresses.build
  end

  def index
    @addresses = current_user.addresses.all
  end

  def edit
  end

  def show
  end

  def update
    if @address.update(address_params)
      redirect_to wechat_addresses_url
    else
      render :edit
    end
  end

  def create
    @address = current_user.addresses.new(address_params)
    if @address.save
      redirect_to wechat_addresses_url
    else
      render :new
    end
  end

  def destroy
    @address.destroy
    redirect_to wechat_addresses_url
  end

  private

    def set_address
      @address = current_user.addresses.find params[:id]
    end

    def address_params
      params.require(:address).permit(:name, :phone_number, :info)
    end

end

app/controllers/wechat/base_controller.rb
class Wechat::BaseController < ApplicationController
  before_action :authenticate_user!
  layout 'wechat'

  private

  def authenticate_user!
    if user_signed_in?
      super
    else
      store_location
      redirect_to user_wechat_omniauth_authorize_path
    end
  end

end

app/controllers/wechat/carts_controller.rb
class Wechat::CartsController < Wechat::BaseController

  def add
    @menu = Menu.find_by(id: params[:id])
    store_cart = "store#{@menu.store_id}"
    @cart = Cart.from_hash(session[store_cart.to_sym])
    @cart.add_item(@menu.id)
    session[store_cart.to_sym] = @cart.serialize
    respond_to do |format|
      format.html { redirect_to wechat_store_url(@menu.store_id) }
      format.js
    end
  end

  def minus
    @menu = Menu.find_by(id: params[:id])
    store_cart = "store#{@menu.store_id}"
    @cart = Cart.from_hash(session[store_cart.to_sym])
    @cart.remove_item(@menu.id)
    session[store_cart.to_sym] = @cart.serialize

    respond_to do |format|
      format.html { redirect_to wechat_store_url(@menu.store_id) }
      format.js
    end
  end

  def destroy
    @store = Store.find params[:store_id]
    store_cart = "store#{@store.id}"
    session[store_cart.to_sym] = nil

    redirect_to wechat_store_url(@store)
  end
end

app/controllers/wechat/orders_controller.rb
class Wechat::OrdersController < Wechat::BaseController

  def new
    store_cart = "store#{params[:store_id]}"
    @order = current_user.orders.build(store_id: params[:store_id],
                                       menus: session[store_cart].to_json)
  end

  def create
    @order = current_user.orders.new(order_params)
    if @order.save
      store_cart = "store#{@order.store_id}"
      session[store_cart] = nil
      redirect_to new_wechat_payment_path(order_id: @order.id)
    else
      render :new
    end
  end

  def index
    @orders = current_user.active_orders
  end

  def show
    @order = Order.where(active: true).find_by(id: params[:id])
  end

  def destroy
    @order = Order.find(params[:id])
    if %w(confirmed refunded delivered).include? @order.state
      debugger
      @order.active = false
      @order.save
    else
      @order.destroy
    end
    redirect_to wechat_orders_url, notice: '订单删除成功'
  end

  private

  def order_params
    params.require(:order).permit(:store_id, :menus, :address_id)
  end
end

app/controllers/wechat/payments_controller.rb
class Wechat::PaymentsController < Wechat::BaseController
  skip_before_action :verify_authenticity_token, only: :notify

  def new
    @order = current_user.orders.find_by(id: params[:order_id])
  end

  def show
    @order = current_user.orders.find_by(id: params[:order_id])
  end

  def create
    @order = current_user.orders.find_by(id: params[:order_id])
    if @order and @order.may_pay?
      @order.pay
      @order.paid_at = Time.now
      @order.save
      redirect_to wechat_payment_url(order_id: @order.id)
    else
      redirect_to wechat_orders_url
    end
  end

  def done
  end

  def notify
  end
end

app/controllers/wechat/stores_controller.rb
class Wechat::StoresController < Wechat::BaseController

  def index
    @q = Store.ransack(params[:q])
    @stores = @q.result.includes(:location)
  end

  def show
    @store = Store.find params[:id]
    store_cart = "store#{@store.id}"
    @cart = Cart.from_hash(session[store_cart.to_sym])
    # 删除客服端里的 session 仍然保存着的商家删除或下线的菜品
    @cart.items.delete_if { |item| !item.menu.publish? || item.menu.nil? }
    session[store_cart.to_sym] = @cart.serialize
  end
end

app/controllers/wechat/users_controller.rb
class Wechat::UsersController < Wechat::BaseController
  before_action :confirm_wechat_user

  def show
  end

  private

  def confirm_wechat_user
    unless current_user.provider == 'wechat'
      redirect_to wechat_stores_url
    end
  end

end

app/controllers/wechats_controller.rb
class WechatsController < ActionController::Base
  wechat_responder

  # 默认文字信息responder
  on :text do |request, content|
    request.reply.text "echo: #{content}" #Just echo
  end

  # 当请求的文字信息内容为'help'时, 使用这个responder处理
  on :text, with: 'help' do |request|
    request.reply.text 'help content' #回复帮助信息
  end

  # 当请求的文字信息内容为'<n>条新闻'时, 使用这个responder处理, 并将n作为第二个参数
  on :text, with: /^(\d+)条新闻$/ do |request, count|
    # 微信最多显示8条新闻，大于8条将只取前8条
    news = (1..count.to_i).each_with_object([]) { |n, memo| memo << { title: '新闻标题', content: "第#{n}条新闻的内容#{n.hash}" } }
    request.reply.news(news) do |article, n, index| # 回复"articles"
      article.item title: "#{index} #{n[:title]}", description: n[:content], pic_url: 'http://www.baidu.com/img/bdlogo.gif', url: 'http://www.baidu.com/'
    end
  end

  # 当用户加关注
  on :event, with: 'subscribe' do |request|
    request.reply.text "User #{request[:FromUserName]} subscribe now"
  end

  # 公众号收到未关注用户扫描qrscene_xxxxxx二维码时。注意此次扫描事件将不再引发上条的用户加关注事件
  on :scan, with: 'qrscene_xxxxxx' do |request, ticket|
    request.reply.text "Unsubscribe user #{request[:FromUserName]} Ticket #{ticket}"
  end

  # 公众号收到已关注用户扫描创建二维码的scene_id事件时
  on :scan, with: 'scene_id' do |request, ticket|
    request.reply.text "Subscribe user #{request[:FromUserName]} Ticket #{ticket}"
  end

  # 当没有任何on :scan事件处理已关注用户扫描的scene_id时
  on :event, with: 'scan' do |request|
    if request[:EventKey].present?
      request.reply.text "event scan got EventKey #{request[:EventKey]} Ticket #{request[:Ticket]}"
    end
  end

  # 企业号收到EventKey 为二维码扫描结果事件时
  on :scan, with: 'BINDING_QR_CODE' do |request, scan_result, scan_type|
    request.reply.text "User #{request[:FromUserName]} ScanResult #{scan_result} ScanType #{scan_type}"
  end

  # 企业号收到EventKey 为CODE 39码扫描结果事件时
  on :scan, with: 'BINDING_BARCODE' do |message, scan_result|
    if scan_result.start_with? 'CODE_39,'
      message.reply.text "User: #{message[:FromUserName]} scan barcode, result is #{scan_result.split(',')[1]}"
    end
  end

  # 当用户点击菜单时
  on :click, with: 'BOOK_LUNCH' do |request, key|
    request.reply.text "User: #{request[:FromUserName]} click #{key}"
  end

  # 当用户点击菜单时
  on :view, with: 'http://wechat.somewhere.com/view_url' do |request, view|
    request.reply.text "#{request[:FromUserName]} view #{view}"
  end

  # 处理图片信息
  on :image do |request|
    request.reply.image(request[:MediaId]) #直接将图片返回给用户
  end

  # 处理语音信息
  on :voice do |request|
    request.reply.voice(request[:MediaId]) #直接语音音返回给用户
  end

  # 处理视频信息
  on :video do |request|
    nickname = wechat.user(request[:FromUserName])['nickname'] #调用 api 获得发送者的nickname
    request.reply.video(request[:MediaId], title: '回声', description: "#{nickname}发来的视频请求") #直接视频返回给用户
  end

  # 处理地理位置消息
  on :label_location do |request|
    request.reply.text("Label: #{request[:Label]} Location_X: #{request[:Location_X]} Location_Y: #{request[:Location_Y]} Scale: #{request[:Scale]}")
  end

  # 处理上报地理位置事件
  on :location do |request|
    request.reply.text("Latitude: #{request[:Latitude]} Longitude: #{request[:Longitude]} Precision: #{request[:Precision]}")
  end

  # 当用户取消关注订阅
  on :event, with: 'unsubscribe' do |request|
    request.reply.success # user can not receive this message
  end

  # 成员进入应用的事件推送
  on :event, with: 'enter_agent' do |request|
    request.reply.text "#{request[:FromUserName]} enter agent app now"
  end

  # 当异步任务增量更新成员完成时推送
  on :batch_job, with: 'sync_user' do |request, batch_job|
    request.reply.text "job #{batch_job[:JobId]} finished, return code #{batch_job[:ErrCode]}, return message #{batch_job[:ErrMsg]}"
  end

  # 当异步任务全量覆盖成员完成时推送
  on :batch_job, with: 'replace_user' do |request, batch_job|
    request.reply.text "job #{batch_job[:JobId]} finished, return code #{batch_job[:ErrCode]}, return message #{batch_job[:ErrMsg]}"
  end

  # 当异步任务邀请成员关注完成时推送
  on :batch_job, with: 'invite_user' do |request, batch_job|
    request.reply.text "job #{batch_job[:JobId]} finished, return code #{batch_job[:ErrCode]}, return message #{batch_job[:ErrMsg]}"
  end

  # 当异步任务全量覆盖部门完成时推送
  on :batch_job, with: 'replace_party' do |request, batch_job|
    request.reply.text "job #{batch_job[:JobId]} finished, return code #{batch_job[:ErrCode]}, return message #{batch_job[:ErrMsg]}"
  end

  # 事件推送群发结果
  on :event, with: 'masssendjobfinish' do |request|
    # https://mp.weixin.qq.com/wiki?action=doc&id=mp1481187827_i0l21&t=0.03571905015619936#8
    request.reply.success # request is XML result hash.
  end

  # 当无任何responder处理用户信息时,使用这个responder处理
  on :fallback, respond: 'fallback message'
end

app/helpers/stores_helper.rb
module StoresHelper
  def stores_for_roles
    current_user.admin? ? @stores = Store.all : @stores = current_user.stores
  end
end

app/helpers/wechat/users_helper.rb
module Wechat::UsersHelper
end

app/views/wechat/stores/index.html.erb
<style>
  .list-group-item {
    text-align: left;
  }
</style>
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>

  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag 'food0.jpg', class: 'd-block w-100', height: 206 %>
    </div>
    <div class="carousel-item">
      <%= image_tag 'food1.jpg', class: 'd-block w-100', height: 206 %>
    </div>
    <div class="carousel-item">
      <%= image_tag 'food2.jpg', class: 'd-block w-100', height: 206 %>
    </div>
    <div class="carousel-item">
      <%= image_tag 'food3.jpg', class: 'd-block w-100', height: 206 %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="container my-3">

  <div class="row">
    <div class="col-5">
      <%= search_form_for [:wechat, @q] do |f| %>

        <div class="form-group">
          <%= f.collection_select :location_id_eq, Location.all,
                                  :id, :name,
                                  {include_blank: '选择食堂'},
                                  {class: 'form-control'} %>
        </div>
      <% end %>
    </div>
  </div>

  <script>
    $('#q_location_id_eq').change(function () {
        $( "#store_search" ).submit();
        console.log($(this).val());
    });
  </script>

  <div class="list-group">
    <% @stores.each_with_index do |store, index| %>
      <a href="<%= wechat_store_path(store) %>" class="list-group-item list-group-item-action bg-light my-1">
        <div class="row">

          <div class="col-4 align-middle">
            <%= image_tag store.picture.url, width: 80, height: 80 %>
          </div>

          <div class="col-8">
            <%= store.name %><br>
            <small><%= truncate store.intro %></small>
            <br>
            <small><%= truncate store.location.name %></small>
          </div>
        </div>
      </a>
    <% end %>
  </div>

</div>

<script type="text/javascript">
  (function ($) {
      $(".home").hide();
      $(".home-click").show();
    })(jQuery);
  window.onload = function(){
      $(".home").hide();
      $(".home-click").show();
    }
</script>

app/views/wechat/stores/show.html.erb
 <style>
  .list-group-item {
    text-align: left;
  }
</style>
<div class="bg text-center"><img src="<%= image_path("close.png") %>" class="close1" ></div>
<div class="container show-store">
  <div class="container text-center store-name"><%= @store.name %></div>
  <div class="col-2 pl-0 fl">
            <%= image_tag "food0.jpg", width: 50, height: 50 %>
  </div>
  <div class="col-10 text-left  pl-0 col-f fl"><%= @store.intro %></div>
</div>

<div class="container" style="height: 40px; border-bottom: 1px solid #EEEEEE">
  <div class="col-6  fl text-center" style="height:38px;line-height: 38px;color: #666">
  <div class="act1 act" style="margin-left:37.5%;height:38px;line-height: 38px;color: #666;width:25%">点菜</div>
  </div>
  <div class="col-6  fl  text-center" style="height:38px;line-height: 38px;color: #666">
    <div class="act act2" style="margin-left:37.5%;height:38px;line-height: 38px;color: #666;width:25%">商家</div>
  </div>
  </div>
</div>
<div class="menu-all">
<div class="container my-1 fl menu-classify" style="width: 25%;">菜单分类</div>
<div class=" fl" style="width: 74%;margin-left: 1%;">

  <div class="list-group">
    <% @store.menus.published.each_with_index do |menu, index| %>
      <li class="list-group-item menu-infor list-group-item-action my-1" style="height: 120px;">
        <div class=""  style="height: 100px;">
          <div class="fl menu-click" data-menu="<%= menu.id %>">
            <a data-toggle="modal" data-target="#exampleModal">
              <%= image_tag menu.pictures[0].url, width: 75, height: 75 %>
            </a>
          </div>

          <div class="col-8  ovf-h fl h-30 menu-click" data-menu="<%= menu.id %>">
           <%= menu.name %>
           
          </div>
          <div class="col-8  ovf-h fl h-20 menu-click" data-menu="<%= menu.id %>">
            <%= menu.intro %>
          </div>
          <div class="col-4  h-30 fl price<%= index + 1 %> menu-click" data-menu="<%= menu.id %>" style="color: red">
           ￥<%= menu.real_price  %>
          </div>
           

              <div class="add fr add<%= index + 1 %> cart-add<%= menu.id %>" data-add="<%= index + 1 %>">
                <%= link_to add_wechat_cart_path(menu), method: :post, remote: true, class: '' do %>
                  <%= image_tag 'add1.png', width: 22 %>
                <% end %>

              </div>
              
              <span id="menu-<%= menu.id %>" class="mr-10 fr columns dpn columns<%= index + 1 %> quantity<%= menu.id %>" data-columns="<%= index + 1 %>"><%= @cart.item_quantity(menu)%></span>
              
              
              <div class="minus mr-10 fr minus<%= index + 1 %> dpn cart-minus<%= menu.id %>" data-minus="<%= index + 1 %>">
                <%= link_to minus_wechat_cart_path(menu), method: :delete, remote: true, class: '' do %>
                  <%= image_tag 'minus1.png', width: 22 %>
                <% end %>
              </div>
        </div>
      </li>

      <div class="menu-det menu-det<%= menu.id %> dpn">
        <%= image_tag menu.pictures[0].url, class: 'd-block',style: "width: 100%;height:200px;" %>
        <div class="container" style="font-size:24px;font-weight: 500">
          <%= menu.name %>
        </div>
        <div class="container" style="color:red;font-size:20px;">
          <b>￥<%= menu.real_price %></b>
        </div>
        <div style="width:100%;border-top: 2px solid #FAFAFA"></div>
        &nbsp;&nbsp;&nbsp;<small style="color: #989797;">商品信息</small> <br>
        <div class="container-fluid" style="color: #666;padding-bottom: 5px;">
          <%= menu.intro %>
        </div>
        
      </div>
      <!-- Modal -->
      <!-- <div class="modal fade menu-det<%= menu.id %>" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" >
        <div class="modal-dialog" role="document">
          <div class="modal-content" >
            <%= image_tag menu.pictures[0].url, class: 'd-block',style: "height:200px;" %>
            <div class="container" style="font-size:18px">
              <%= menu.name %>
            </div>
            <div class="container" style="color:red;font-size:16px;">
              ￥<%= menu.real_price %>
            </div>
            <div style="width:100%;border-top: 2px solid #FAFAFA"></div>
            <div class="container-fluid" style="color: #333;">
              <%= menu.intro %>
            </div>
             <button type="button" class="close" data-dismiss="modal" aria-label="Close">
               <span aria-hidden="true">&times;</span>
            </button>
          </div>
        </div>
      </div> -->
    <% end %>
    <div style="height:120px;"></div>
  </div>
</div>
</div>
<div class="store-all dpn">
  <div class="store-det">
      <img src="<%= image_path("address.png") %>" class="store-det-img">
      <span class="store-det-des">营业地址: <%= truncate @store.location.name %></span>
      <img src="<%= image_path("phone.png") %>" class="store-all-img">
    </div>
    <div class="store-det">
      <img src="<%= image_path("safe.png") %>" class="store-det-img">
      <span class="store-det-des">查看食品安全档案</span>
      <img src="<%= image_path("a.png") %>" class="store-all-img"></a>
    </div>
      <div class="store-det">
        <img src="<%= image_path("time.png") %>" class="store-det-img fl">
        
          <span class="store-det-des fl">营业时间: 
            <% if @store.business_hours[0].nil? %>
              暂无
            <% else%>
              <% i = 0 %>
              <% while i< @store.business_hours.length %>
              <%= (@store.business_hours[i].open_at).strftime("%H:%M") %>~<%= (@store.business_hours[i].close_at).strftime("%H:%M") %> 
              <% i += 1 %>
              <% end %>
            <% end %>
          </span>
      </div>
</div>
<div class="footer-cart">
  <div class="fixed-cart-btn fl dpn">
    <!-- Button trigger modal -->
      <a id="cart" style=" display: <%= @cart.total_quantity != 0 ? 'true' : 'none' %>;" data-toggle="modal" data-target="#store-<%= @store.id %>-cart-modal">
          <%= image_tag 'fi-cart.png', class: 'cart', width: 30, height:30 %>

        <div id="store-<%= @store.id %>-cart" class="cart-column dpn col-f text-center">
          <%= @cart.total_quantity  %>
        </div>
      </a>
  
  </div>
  <div class="col-4  mr-2 cart-price text-center col-f fl dpn">¥<%= @cart.total_price  %></div>
  <div class="no-menu col-5 fr no-pay col-f text-center">未选购商品</div>
  <div class="col-4 fr text-center pay dpn">
    <%= link_to '去结算', new_wechat_order_path(store_id: @store), data: {confirm: '确认支付?'},style: "color:#000" %>
  </div>
</div>
<!-- Modal -->
<div class="modal hide" id="store-<%= @store.id %>-cart-modal" tabindex="-1" role="dialog" aria-labelledby="store-<%= @store.id %>-cart-modal" aria-hidden="true" style="display: none">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <%= image_tag 'empty-cart.png', class: '', width: 15, height:15, style: "margin-top:6px;margin-left:60%" %>
        <%= link_to '清空购物车', wechat_cart_path(store_id: @store), method: :delete, class: 'fr',style: "color:#666666;font-size:14px;margin-top:3px;margin-left:5px;" %>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="cart-<%= @store.id %>" class="modal-body">
        <% unless @cart.empty? %>
          <% @cart.items.each do |item| %>
            <% unless item.quantity == 0 %>
              <%= render 'wechat/carts/cart_menu', item: item %>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <div class="modal-footer">
          <div class="mx-5">
            <strong id="total-price">¥<%= @cart.total_price %></strong>
          </div>
          <div class="text-right">
            
            <%= link_to '去结算', new_wechat_order_path(store_id: @store), class: 'btn btn-sm btn-outline-info', style: "background:#FFD161;border:0px;color: #000;" %>
          </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  (function ($) {
      var total_quantity = parseInt($(".cart-column").html());
      $(".act1").css("border-bottom","0.1rem inset #D99D54"); 
      $(".act1").css("color","#D99D54");
      $(".home").hide();
      $(".home-click").show();
      if (total_quantity > 0) {
        $(".fixed-cart-btn").show();
        $(".cart-column").show();
        $(".no-pay").hide();
        $(".pay").show();
        $(".cart-price").show();
       
        
      }
    })(jQuery);
    window.onload = function(){
      $(".home").hide();
      $(".home-click").show();
    }
    $(".columns").each(function(){
      var column_id = $(this).data("columns");
      if(parseInt($(this).html()) > 0){
        $(this).show();
        $(".minus"+column_id).show();
        $(".add"+column_id).css("margin-top","0");
      }

    })
    $(".add").click(function(){
      var id = $(this).data("add");
      var columns = parseInt($(".columns"+id).html());
      var total_quantity = parseInt($(".cart-column").html());
      var price = parseFloat($(".price"+id).html().substring(1));
      var total_price = <%= @cart.total_price %>;
      if(columns == 0){
        $(".columns"+id).show();
        $(".minus"+id).show();
        $(this).css("margin-top","0");
        $(".fixed-cart-btn").show();
        $(".no-pay").hide();
        $(".pay").show();
        
      }
      if(total_quantity == 0){
        $(".cart-column").show();
        $(".cart-price").show();
      }
    })
    $(".minus").click(function(){
      var id = $(this).data("minus");
      var columns = parseInt($(".columns"+id).html());
      var total_quantity =parseInt($(".cart-column").html());
      var price = parseFloat($(".price"+id).html().substring(1));
      var total_price = parseFloat($(".cart-price").html().substring(1));
      if(columns == 1){
        $(".columns"+id).hide();
        $(this).hide();

      }
      if(total_quantity ==1 ){
        $(".fixed-cart-btn").hide();
        $(".cart-column").hide();
        $(".no-pay").show();
        $(".pay").hide();
        $(".cart-price").hide();
      }
    })
    $(".bg").on('click', function(){
      $(".menu-det").hide();
      $(".bg").css("z-index",0);
      $(".bg").hide();
      $("body").css('position','static');
    })
    $(".close1").on('click', function(){
      $(".menu-det").hide();
      $(".bg").css("z-index",0);
      $(".bg").hide();
      $("body").css('position','static');
    })
    $(".act").click(function(){
      $(".act").css("color","#666");
      $(".act").css("border-bottom","0");
      $(this).css("color","#D99D54");
      $(this).css("border-bottom","0.1rem inset #D99D54");
    })
    $("#cart").click(function(){
      $("#store-<%= @store.id %>-cart-modal").show();
    })
    $(".menu-click").click(function(){
      var id = $(this).data("menu"); 
      var height = $(".menu-det"+id).height() + 90 + "px";
      $(".close1").css("top",height);
      $(".bg").css('z-index','10');
      $(".bg").show();
      $(".menu-det"+id).show();
     

    })
    $(".act1").click(function(){
      $(".menu-all").show();
      $(".store-all").hide();
    })
    $(".act2").click(function(){
      $(".store-all").show();
      $(".menu-all").hide();
    })
</script> 