config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resource :wechat, only: %i( show create )
  namespace :wechat do
    resources :stores, only: %i( index show )
    resource :cart, only: :destroy do
      collection do
        post :add, path: 'add/:id'
        delete :minus, path: 'minus/:id'
      end
    end
    resources :users, only: %i( show )
    resources :orders, only: %i( new index show create destroy )
    resources :addresses
    resource :payment, only: %i( new create show) do
      get :done
      post :notify
    end
  end
  get 'auth/wechat/callback', to: 'home#wechat'

  devise_for :users, :controllers => {
      :omniauth_callbacks => "users/omniauth_callbacks",
  }

  resources :users, except: %i( new create ) do
    member do
      patch :rolify
    end
  end
  resources :menus do
    member do
      get 'pictures', to: 'menus#list'
      post 'pictures', to: 'menus#upload'
      delete 'pictures/:picture_id', to: 'menus#remove'

      post :publish
      post :unpublish
    end
  end
  resources :locations
  resources :stores
  resources :orders do
    member do
      post :confirm
    end
  end

  require 'sidekiq/web'
  authenticate :user, lambda {|u| u.admin?} do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/controllers/wechat/addresses_controller.rb
class Wechat::AddressesController < Wechat::BaseController
  before_action :set_address, only: %i( edit show update destroy )

  def new
    @address = current_user.addresses.build
  end

  def index
    @addresses = current_user.addresses.all
  end

  def edit
  end

  def show
  end

  def update
    if @address.update(address_params)
      redirect_to wechat_addresses_url
    else
      render :edit
    end
  end

  def create
    @address = current_user.addresses.new(address_params)
    if @address.save
      redirect_to wechat_addresses_url
    else
      render :new
    end
  end

  def destroy
    @address.destroy
    redirect_to wechat_addresses_url
  end

  private

    def set_address
      @address = current_user.addresses.find params[:id]
    end

    def address_params
      params.require(:address).permit(:name, :phone_number, :info)
    end

end

app/controllers/wechat/base_controller.rb
class Wechat::BaseController < ApplicationController
  before_action :authenticate_user!
  layout 'wechat'

  private

  def authenticate_user!
    if user_signed_in?
      super
    else
      store_location
      redirect_to user_wechat_omniauth_authorize_path
    end
  end

end

app/controllers/wechat/carts_controller.rb
class Wechat::CartsController < Wechat::BaseController

  def add
    @menu = Menu.find_by(id: params[:id])
    store_cart = "store#{@menu.store_id}"
    @cart = Cart.from_hash(session[store_cart.to_sym])
    @cart.add_item(@menu.id)
    session[store_cart.to_sym] = @cart.serialize
    respond_to do |format|
      format.html { redirect_to wechat_store_url(@menu.store_id) }
      format.js
    end
  end

  def minus
    @menu = Menu.find_by(id: params[:id])
    store_cart = "store#{@menu.store_id}"
    @cart = Cart.from_hash(session[store_cart.to_sym])
    @cart.remove_item(@menu.id)
    session[store_cart.to_sym] = @cart.serialize

    respond_to do |format|
      format.html { redirect_to wechat_store_url(@menu.store_id) }
      format.js
    end
  end

  def destroy
    @store = Store.find params[:store_id]
    store_cart = "store#{@store.id}"
    session[store_cart.to_sym] = nil

    redirect_to wechat_store_url(@store)
  end
end

app/controllers/wechat/orders_controller.rb
class Wechat::OrdersController < Wechat::BaseController

  def new
    store_cart = "store#{params[:store_id]}"
    @order = current_user.orders.build(store_id: params[:store_id],
                                       menus: session[store_cart].to_json)
  end

  def create
    @order = current_user.orders.new(order_params)
    if @order.save
      store_cart = "store#{@order.store_id}"
      session[store_cart] = nil
      redirect_to new_wechat_payment_path(order_id: @order.id)
    else
      render :new
    end
  end

  def index
    @orders = current_user.active_orders
  end

  def show
    @order = Order.where(active: true).find_by(id: params[:id])
  end

  def destroy
    @order = Order.find(params[:id])
    if %w(confirmed refunded delivered).include? @order.state
      debugger
      @order.active = false
      @order.save
    else
      @order.destroy
    end
    redirect_to wechat_orders_url, notice: '订单删除成功'
  end

  private

  def order_params
    params.require(:order).permit(:store_id, :menus, :address_id)
  end
end

app/controllers/wechat/payments_controller.rb
class Wechat::PaymentsController < Wechat::BaseController
  skip_before_action :verify_authenticity_token, only: :notify

  def new
    @order = current_user.orders.find_by(id: params[:order_id])
  end

  def show
    @order = current_user.orders.find_by(id: params[:order_id])
  end

  def create
    @order = current_user.orders.find_by(id: params[:order_id])
    if @order and @order.may_pay?
      @order.pay
      @order.paid_at = Time.now
      @order.save
      redirect_to wechat_payment_url(order_id: @order.id)
    else
      redirect_to wechat_orders_url
    end
  end

  def done
  end

  def notify
  end
end

app/controllers/wechat/stores_controller.rb
class Wechat::StoresController < Wechat::BaseController

  def index
    @q = Store.ransack(params[:q])
    @stores = @q.result.includes(:location)
  end

  def show
    @store = Store.find params[:id]
    store_cart = "store#{@store.id}"
    @cart = Cart.from_hash(session[store_cart.to_sym])
    # 删除客服端里的 session 仍然保存着的商家删除或下线的菜品
    @cart.items.delete_if { |item| !item.menu.publish? || item.menu.nil? }
    session[store_cart.to_sym] = @cart.serialize
  end
end

app/controllers/wechat/users_controller.rb
class Wechat::UsersController < Wechat::BaseController
  before_action :confirm_wechat_user

  def show
  end

  private

  def confirm_wechat_user
    unless current_user.provider == 'wechat'
      redirect_to wechat_stores_url
    end
  end

end

app/controllers/wechats_controller.rb
class WechatsController < ActionController::Base
  wechat_responder

  # 默认文字信息responder
  on :text do |request, content|
    request.reply.text "echo: #{content}" #Just echo
  end

  # 当请求的文字信息内容为'help'时, 使用这个responder处理
  on :text, with: 'help' do |request|
    request.reply.text 'help content' #回复帮助信息
  end

  # 当请求的文字信息内容为'<n>条新闻'时, 使用这个responder处理, 并将n作为第二个参数
  on :text, with: /^(\d+)条新闻$/ do |request, count|
    # 微信最多显示8条新闻，大于8条将只取前8条
    news = (1..count.to_i).each_with_object([]) { |n, memo| memo << { title: '新闻标题', content: "第#{n}条新闻的内容#{n.hash}" } }
    request.reply.news(news) do |article, n, index| # 回复"articles"
      article.item title: "#{index} #{n[:title]}", description: n[:content], pic_url: 'http://www.baidu.com/img/bdlogo.gif', url: 'http://www.baidu.com/'
    end
  end

  # 当用户加关注
  on :event, with: 'subscribe' do |request|
    request.reply.text "User #{request[:FromUserName]} subscribe now"
  end

  # 公众号收到未关注用户扫描qrscene_xxxxxx二维码时。注意此次扫描事件将不再引发上条的用户加关注事件
  on :scan, with: 'qrscene_xxxxxx' do |request, ticket|
    request.reply.text "Unsubscribe user #{request[:FromUserName]} Ticket #{ticket}"
  end

  # 公众号收到已关注用户扫描创建二维码的scene_id事件时
  on :scan, with: 'scene_id' do |request, ticket|
    request.reply.text "Subscribe user #{request[:FromUserName]} Ticket #{ticket}"
  end

  # 当没有任何on :scan事件处理已关注用户扫描的scene_id时
  on :event, with: 'scan' do |request|
    if request[:EventKey].present?
      request.reply.text "event scan got EventKey #{request[:EventKey]} Ticket #{request[:Ticket]}"
    end
  end

  # 企业号收到EventKey 为二维码扫描结果事件时
  on :scan, with: 'BINDING_QR_CODE' do |request, scan_result, scan_type|
    request.reply.text "User #{request[:FromUserName]} ScanResult #{scan_result} ScanType #{scan_type}"
  end

  # 企业号收到EventKey 为CODE 39码扫描结果事件时
  on :scan, with: 'BINDING_BARCODE' do |message, scan_result|
    if scan_result.start_with? 'CODE_39,'
      message.reply.text "User: #{message[:FromUserName]} scan barcode, result is #{scan_result.split(',')[1]}"
    end
  end

  # 当用户点击菜单时
  on :click, with: 'BOOK_LUNCH' do |request, key|
    request.reply.text "User: #{request[:FromUserName]} click #{key}"
  end

  # 当用户点击菜单时
  on :view, with: 'http://wechat.somewhere.com/view_url' do |request, view|
    request.reply.text "#{request[:FromUserName]} view #{view}"
  end

  # 处理图片信息
  on :image do |request|
    request.reply.image(request[:MediaId]) #直接将图片返回给用户
  end

  # 处理语音信息
  on :voice do |request|
    request.reply.voice(request[:MediaId]) #直接语音音返回给用户
  end

  # 处理视频信息
  on :video do |request|
    nickname = wechat.user(request[:FromUserName])['nickname'] #调用 api 获得发送者的nickname
    request.reply.video(request[:MediaId], title: '回声', description: "#{nickname}发来的视频请求") #直接视频返回给用户
  end

  # 处理地理位置消息
  on :label_location do |request|
    request.reply.text("Label: #{request[:Label]} Location_X: #{request[:Location_X]} Location_Y: #{request[:Location_Y]} Scale: #{request[:Scale]}")
  end

  # 处理上报地理位置事件
  on :location do |request|
    request.reply.text("Latitude: #{request[:Latitude]} Longitude: #{request[:Longitude]} Precision: #{request[:Precision]}")
  end

  # 当用户取消关注订阅
  on :event, with: 'unsubscribe' do |request|
    request.reply.success # user can not receive this message
  end

  # 成员进入应用的事件推送
  on :event, with: 'enter_agent' do |request|
    request.reply.text "#{request[:FromUserName]} enter agent app now"
  end

  # 当异步任务增量更新成员完成时推送
  on :batch_job, with: 'sync_user' do |request, batch_job|
    request.reply.text "job #{batch_job[:JobId]} finished, return code #{batch_job[:ErrCode]}, return message #{batch_job[:ErrMsg]}"
  end

  # 当异步任务全量覆盖成员完成时推送
  on :batch_job, with: 'replace_user' do |request, batch_job|
    request.reply.text "job #{batch_job[:JobId]} finished, return code #{batch_job[:ErrCode]}, return message #{batch_job[:ErrMsg]}"
  end

  # 当异步任务邀请成员关注完成时推送
  on :batch_job, with: 'invite_user' do |request, batch_job|
    request.reply.text "job #{batch_job[:JobId]} finished, return code #{batch_job[:ErrCode]}, return message #{batch_job[:ErrMsg]}"
  end

  # 当异步任务全量覆盖部门完成时推送
  on :batch_job, with: 'replace_party' do |request, batch_job|
    request.reply.text "job #{batch_job[:JobId]} finished, return code #{batch_job[:ErrCode]}, return message #{batch_job[:ErrMsg]}"
  end

  # 事件推送群发结果
  on :event, with: 'masssendjobfinish' do |request|
    # https://mp.weixin.qq.com/wiki?action=doc&id=mp1481187827_i0l21&t=0.03571905015619936#8
    request.reply.success # request is XML result hash.
  end

  # 当无任何responder处理用户信息时,使用这个responder处理
  on :fallback, respond: 'fallback message'
end

app/helpers/wechat/users_helper.rb
module Wechat::UsersHelper
end

app/views/wechat/addresses/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="<%= wechat_addresses_path %>">
    地址管理
  </a>
</nav>

app/views/wechat/addresses/edit.html.erb
<%= render 'wechat/addresses/nav' %>

<div class="container">

  <%= form_for [:wechat, @address] do |f| %>
    <div class="form-group row">
      <%= f.label :name, '姓名', class: 'col-3 col-form-label' %>
      <div class="col-9">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :phone_number, '手机号', class: 'col-3 col-form-label' %>
      <div class="col-9">
        <%= f.phone_field :phone_number, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :info, '地址', class: 'col-3 col-form-label' %>
      <div class="col-9">
        <%= f.text_field :info, class: 'form-control' %>
      </div>
    </div>

    <div class="text-right">
      <%= f.submit '确认', class: 'btn btn-sm btn-outline-info' %>
    </div>
  <% end %>
</div>

app/views/wechat/addresses/index.html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="<%= wechat_addresses_path %>">
    地址管理
  </a>
</nav>

<div class="container">
  <div class="list-group">
    <% @addresses.each do |address| %>
      <a href="<%= wechat_address_path(address) %>" class="list-group-item list-group-item-action bg-light my-1 text-left">
        <%= address.name %>-<%= address.phone_number %><br>
        <%= address.info %><br>
      </a>
    <% end %>
  </div>
  <br>
  <div class="text-right">
    <%= link_to '添加地址', new_wechat_address_path, class: 'btn btn-sm btn-outline-info' %>
  </div>
</div>

app/views/wechat/addresses/new.html.erb
<%= render 'wechat/addresses/nav' %>

<div class="container">

  <%= form_for [:wechat, @address] do |f| %>
    <div class="form-group row">
      <%= f.label :name, '姓名', class: 'col-3 col-form-label' %>
      <div class="col-9">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :phone_number, '手机号', class: 'col-3 col-form-label' %>
      <div class="col-9">
        <%= f.phone_field :phone_number, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :info, '地址', class: 'col-3 col-form-label' %>
      <div class="col-9">
        <%= f.text_field :info, class: 'form-control' %>
      </div>
    </div>

    <div class="text-right">
      <%= f.submit '确认', class: 'btn btn-sm btn-outline-info' %>
    </div>
  <% end %>
</div>

app/views/wechat/addresses/show.html.erb
<%= render 'wechat/addresses/nav' %>

<div class="container">
  <div class="list-group">
    <a href="<%= edit_wechat_address_path(@address) %>" class="list-group-item list-group-item-action bg-light my-1 text-left">
      <%= @address.name %>-<%= @address.phone_number %><br>
      <%= @address.info %><br>
    </a>
  </div>
  <br>
  <div class="text-right">
    <%= link_to '编辑', edit_wechat_address_path(@address), class: 'btn btn-sm btn-outline-info' %>
    <%= link_to '删除', wechat_address_path(@address), method: :delete, class: 'btn btn-sm btn-outline-info' %>
  </div>
</div>